/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyApplicationsIndexRouteImport } from './routes/my-applications/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as PetsPetIdRouteImport } from './routes/pets/$petId'
import { Route as ApplyPetIdRouteImport } from './routes/apply/$petId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyApplicationsIndexRoute = MyApplicationsIndexRouteImport.update({
  id: '/my-applications/',
  path: '/my-applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsPetIdRoute = PetsPetIdRouteImport.update({
  id: '/pets/$petId',
  path: '/pets/$petId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyPetIdRoute = ApplyPetIdRouteImport.update({
  id: '/apply/$petId',
  path: '/apply/$petId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/apply/$petId': typeof ApplyPetIdRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/account/': typeof AccountIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/my-applications/': typeof MyApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/apply/$petId': typeof ApplyPetIdRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/account': typeof AccountIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/my-applications': typeof MyApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/apply/$petId': typeof ApplyPetIdRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/account/': typeof AccountIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/my-applications/': typeof MyApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/apply/$petId'
    | '/pets/$petId'
    | '/account/'
    | '/dashboard/'
    | '/my-applications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/apply/$petId'
    | '/pets/$petId'
    | '/account'
    | '/dashboard'
    | '/my-applications'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/apply/$petId'
    | '/pets/$petId'
    | '/account/'
    | '/dashboard/'
    | '/my-applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApplyPetIdRoute: typeof ApplyPetIdRoute
  PetsPetIdRoute: typeof PetsPetIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  MyApplicationsIndexRoute: typeof MyApplicationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-applications/': {
      id: '/my-applications/'
      path: '/my-applications'
      fullPath: '/my-applications/'
      preLoaderRoute: typeof MyApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/$petId': {
      id: '/pets/$petId'
      path: '/pets/$petId'
      fullPath: '/pets/$petId'
      preLoaderRoute: typeof PetsPetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$petId': {
      id: '/apply/$petId'
      path: '/apply/$petId'
      fullPath: '/apply/$petId'
      preLoaderRoute: typeof ApplyPetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApplyPetIdRoute: ApplyPetIdRoute,
  PetsPetIdRoute: PetsPetIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  MyApplicationsIndexRoute: MyApplicationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
